import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { BarChart3, Building2, CalendarDays, Download, FileText, Link2, ListChecks, Lock, LogOut, Plus, Printer, RefreshCcw, Save, Settings, Trash2, UserCog, Users } from 'lucide-react';
import './style.css';

const API = 'http://localhost:8000';
const todayISO = () => new Date().toISOString().slice(0, 10);
const firstDayOfMonthISO = () => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().slice(0, 10); };
const formatIQD = v => 'IQD ' + Number(v || 0).toLocaleString('en-US');
const formatSalary = e => (e.salaryCurrency === 'USD' ? 'USD ' : 'IQD ') + Number(e.salary || 0).toLocaleString('en-US');
const compactNumber = v => Number(v || 0).toLocaleString('en-US', { notation: 'compact', maximumFractionDigits: 1 });
const pageLabels = { dashboard: 'Dashboard', entry: 'Daily Entry', reports: 'Reports', branches: 'Branches', employees: 'Employees', social: 'Social Links', audit: 'Audit Log', settings: 'Settings', users: 'Users' };
const allPages = Object.keys(pageLabels);
const read = (k, f) => { try { return JSON.parse(localStorage.getItem(k) || JSON.stringify(f)); } catch { return f; } };
const write = (k, v) => localStorage.setItem(k, JSON.stringify(v));

function Chart({ data }) {
  const rows = (data || []).map(x => ({ ...x, label: String(x.date || '').slice(5) }));
  return <div className="rechartBox"><ResponsiveContainer width="100%" height={290}><AreaChart data={rows}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="label" stroke="#a1a1aa"/><YAxis stroke="#a1a1aa" tickFormatter={compactNumber}/><Tooltip contentStyle={{background:'#101217',border:'1px solid rgba(212,175,55,.25)',borderRadius:12,color:'#fff'}} formatter={v=>formatIQD(v)}/><Legend/><Area type="monotone" dataKey="revenue" name="Revenue" stroke="#d4af37" fill="#d4af37" fillOpacity={.18} strokeWidth={3}/><Area type="monotone" dataKey="expenses" name="Expenses" stroke="#ff6b6b" fill="#ff6b6b" fillOpacity={.12} strokeWidth={3}/><Area type="monotone" dataKey="profit" name="Profit" stroke="#53d769" fill="#53d769" fillOpacity={.12} strokeWidth={3}/></AreaChart></ResponsiveContainer></div>;
}

function AuthScreen({ users, onLogin, onCreateFirstAdmin }) {
  const [setup, setSetup] = useState(users.length === 0);
  const [username, setUsername] = useState('');
  const [secret, setSecret] = useState('');
  const [error, setError] = useState('');
  function submit(e) { e.preventDefault(); setError(''); if (setup) return onCreateFirstAdmin(username, secret); const u = users.find(x => x.username === username && x.secret === secret && x.active !== false); if (!u) return setError('Invalid login'); onLogin(u); }
  return <div className="appShell" style={{alignItems:'center',justifyContent:'center',padding:24}}><form className="panel" style={{width:'min(460px,94vw)'}} onSubmit={submit}><div className="brand"><div className="brandLogo">RTT</div><div><h1>Royal Thai Touch</h1><span>{setup ? 'Create Admin User' : 'ERP Login'}</span></div></div><h3><Lock size={18}/> {setup ? 'First Admin Setup' : 'Login'}</h3>{error&&<div className="notice">{error}</div>}<label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)} autoFocus/><label>Password</label><input type="password" value={secret} onChange={e=>setSecret(e.target.value)}/><button className="primaryBtn">{setup ? 'Create Admin' : 'Login'}</button></form></div>;
}

function App() {
  const [users, setUsers] = useState(() => read('rtt_users', []));
  const [current, setCurrent] = useState(() => read('rtt_current_user', null));
  const [page, setPage] = useState('dashboard');
  const [businessDate, setBusinessDate] = useState(todayISO());
  const [dashboard, setDashboard] = useState(null);
  const [trend, setTrend] = useState([]);
  const [branches, setBranches] = useState([]);
  const [auditLogs, setAuditLogs] = useState([]);
  const [message, setMessage] = useState('');
  const [report, setReport] = useState(null);
  const [reportRange, setReportRange] = useState({ from: firstDayOfMonthISO(), to: todayISO() });
  const [reportOptions, setReportOptions] = useState({ branch_id: '', report_mode: 'full' });
  const [branchForm, setBranchForm] = useState({ name: '', address: 'Erbil' });
  const [employees, setEmployees] = useState(() => read('rtt_employees', []));
  const [selectedEmployee, setSelectedEmployee] = useState(null);
  const [socialLinks, setSocialLinks] = useState(() => read('rtt_social_links', {}));
  const [socialBranchId, setSocialBranchId] = useState('');
  const [employeeForm, setEmployeeForm] = useState({ name:'', branch_id:'', role:'', salary:'', salaryCurrency:'IQD', phone:'', profileImage:'', passportImage:'', residenceFrontImage:'', residenceBackImage:'', residenceImage:'' });
  const [socialForm, setSocialForm] = useState({ facebook:'', instagram:'', tiktok:'', whatsapp:'', website:'', notes:'' });
  const [userForm, setUserForm] = useState({ username:'', secret:'', role:'Staff', permissions:['dashboard','entry'], allowedBranches:[], active:true });
  const [entry, setEntry] = useState({ branch_id:'', business_date:todayISO(), revenue:'', notes:'', expenses:[{ category:'Other Expenses', amount:'', notes:'' }] });

  const can = p => current?.permissions?.includes(p);
  const allowed = id => !current?.allowedBranches?.length || current.allowedBranches.includes(String(id));
  const visibleBranches = branches.filter(b => allowed(b.id));
  const visibleIds = new Set(visibleBranches.map(b => String(b.id)));
  const visibleRows = (dashboard?.branches || []).filter(r => allowed(r.branch_id));
  const visibleEmployees = employees.filter(e => !current?.allowedBranches?.length || visibleIds.has(String(e.branch_id)) || visibleBranches.some(b => b.name === e.branch));
  const reportQuery = () => { const p = new URLSearchParams({ date_from:reportRange.from, date_to:reportRange.to, report_mode:reportOptions.report_mode }); if (reportOptions.branch_id) p.set('branch_id', reportOptions.branch_id); return p.toString(); };

  useEffect(() => write('rtt_users', users), [users]);
  useEffect(() => current ? write('rtt_current_user', current) : localStorage.removeItem('rtt_current_user'), [current]);
  useEffect(() => write('rtt_employees', employees), [employees]);
  useEffect(() => write('rtt_social_links', socialLinks), [socialLinks]);
  useEffect(() => { if (current) loadData().catch(()=>setMessage('Backend is starting. Please wait 30 seconds then refresh.')); }, [current]);
  useEffect(() => { if (current && !can(page)) setPage(current.permissions?.[0] || 'dashboard'); }, [current, page]);

  async function api(path, options={}) { const r = await fetch(API + path, { ...options, headers:{ 'Content-Type':'application/json', ...(options.headers||{}) } }); if (!r.ok) throw new Error((await r.json().catch(()=>({}))).detail || 'Request failed'); return r.json(); }
  async function loadData(dateValue=businessDate) { const [d,b,t] = await Promise.all([api(`/dashboard?business_date=${dateValue}`), api('/branches'), api('/dashboard/trend?days=30')]); setDashboard(d); setBranches(b); setTrend(t); const first = b.find(x => !current?.allowedBranches?.length || current.allowedBranches.includes(String(x.id))); if (first) { setEntry(p=>({...p,branch_id: String(first.id)})); setEmployeeForm(p=>({...p, branch_id: p.branch_id || String(first.id)})); setSocialBranchId(p=>p || String(first.id)); } }
  async function loadEntry(branchId=entry.branch_id, dateValue=entry.business_date) { if (!allowed(branchId)) return setMessage('This user is not allowed to access this center'); const d = await api(`/daily-entry?branch_id=${branchId}&business_date=${dateValue}`); setEntry({ branch_id:String(d.branch_id), business_date:d.business_date, revenue:d.revenue ? String(d.revenue) : '', notes:d.notes || '', expenses:d.expenses.length ? d.expenses.map(e=>({category:e.category, amount:String(e.amount), notes:e.notes||''})) : [{ category:'Other Expenses', amount:'', notes:'' }] }); }
  async function saveEntry(e) { e.preventDefault(); if (!allowed(entry.branch_id)) return setMessage('This user cannot enter revenue for this center'); await api('/daily-entry', { method:'POST', body:JSON.stringify({ branch_id:Number(entry.branch_id), business_date:entry.business_date, revenue:Number(entry.revenue||0), notes:entry.notes, expenses:entry.expenses.map(x=>({ category:x.category, amount:Number(x.amount||0), notes:x.notes||'' })) }) }); setMessage('Saved successfully'); await loadData(entry.business_date); }
  async function closeDay() { if (!allowed(entry.branch_id)) return setMessage('This user cannot close this center'); await api(`/daily-entry/close?branch_id=${entry.branch_id}&business_date=${entry.business_date}`, { method:'POST' }); setMessage('Day closed successfully'); }
  async function createBranch(e) { e.preventDefault(); await api('/branches', { method:'POST', body:JSON.stringify({...branchForm, active:true}) }); setBranchForm({name:'',address:'Erbil'}); await loadData(); }
  async function loadReport() { setReport(await api(`/reports/summary?${reportQuery()}`)); }
  async function loadAuditLogs() { setAuditLogs(await api('/audit-logs')); }
  function addExpense(){ setEntry(p=>({...p, expenses:[...p.expenses,{category:'Other Expenses',amount:'',notes:''}]})); }
  function updateExpense(i,k,v){ setEntry(p=>({...p, expenses:p.expenses.map((x,n)=>n===i?{...x,[k]:v}:x)})); }
  function fileToBase64(field,file){ if(!file)return; const r=new FileReader(); r.onload=()=>setEmployeeForm(p=>({...p,[field]:r.result})); r.readAsDataURL(file); }
  function addEmployee(e){ e.preventDefault(); if(!allowed(employeeForm.branch_id)) return setMessage('This user cannot add employees for this center'); const b=branches.find(x=>String(x.id)===String(employeeForm.branch_id)); setEmployees(p=>[{...employeeForm,id:Date.now(),branch:b?.name||'-',salary:Number(employeeForm.salary||0)},...p]); setEmployeeForm({ name:'', branch_id:employeeForm.branch_id, role:'', salary:'', salaryCurrency:'IQD', phone:'', profileImage:'', passportImage:'', residenceFrontImage:'', residenceBackImage:'', residenceImage:'' }); }
  function printEmployee(emp){ const f=emp.residenceFrontImage||emp.residenceImage; const w=window.open('','_blank'); w.document.write(`<html><body style="font-family:Arial;padding:24px"><h1>Royal Thai Touch - Employee File</h1>${emp.profileImage?`<img src="${emp.profileImage}" style="width:130px;height:130px;object-fit:cover"/>`:''}<p><b>Name:</b> ${emp.name}</p><p><b>Center:</b> ${emp.branch}</p><p><b>Job:</b> ${emp.role||'-'}</p><p><b>Salary:</b> ${formatSalary(emp)}</p><p><b>Phone:</b> ${emp.phone||'-'}</p><h3>Passport</h3>${emp.passportImage?`<img src="${emp.passportImage}" style="max-width:100%"/>`:'No image'}<h3>Residence Front</h3>${f?`<img src="${f}" style="max-width:100%"/>`:'No image'}<h3>Residence Back</h3>${emp.residenceBackImage?`<img src="${emp.residenceBackImage}" style="max-width:100%"/>`:'No image'}<script>window.print()</script></body></html>`); w.document.close(); }
  function saveSocialLinks(e){ e.preventDefault(); if(!allowed(socialBranchId)) return setMessage('This user cannot edit this center'); setSocialLinks(p=>({...p,[socialBranchId]:socialForm})); setMessage('Social links saved'); }
  function changeSocialBranch(id){ if(!allowed(id)) return; setSocialBranchId(id); setSocialForm(socialLinks[id] || { facebook:'', instagram:'', tiktok:'', whatsapp:'', website:'', notes:'' }); }
  function openExternal(type, raw){ if(!raw)return; let url=raw.trim(); if(type==='whatsapp'){const phone=url.replace(/[^0-9]/g,''); url=url.startsWith('http')?url:`https://wa.me/${phone}`;} else if(!/^https?:\/\//i.test(url)) url=`https://${url}`; window.open(url,'_blank','noopener,noreferrer'); }
  function addUser(e){ e.preventDefault(); if(users.some(u=>u.username===userForm.username)) return setMessage('Username already exists'); setUsers(p=>[{...userForm,id:Date.now(),permissions:userForm.permissions.length?userForm.permissions:['dashboard'],allowedBranches:userForm.allowedBranches||[]},...p]); setUserForm({ username:'', secret:'', role:'Staff', permissions:['dashboard','entry'], allowedBranches:[], active:true }); setMessage('User created'); }
  function togglePermission(p){ setUserForm(x=>({...x, permissions:x.permissions.includes(p)?x.permissions.filter(y=>y!==p):[...x.permissions,p]})); }
  function toggleBranch(id){ id=String(id); setUserForm(x=>({...x, allowedBranches:(x.allowedBranches||[]).includes(id)?x.allowedBranches.filter(y=>y!==id):[...(x.allowedBranches||[]),id]})); }
  function createFirstAdmin(username, secret){ if(!username || !secret) return; const admin={id:Date.now(),username,secret,role:'Admin',permissions:allPages,allowedBranches:[],active:true}; setUsers([admin]); setCurrent(admin); }
  function nav(k, icon, label, fn){ return can(k) ? <button className={page===k?'active':''} onClick={fn||(()=>setPage(k))}>{icon} {label}</button> : null; }

  const expenseTotal=useMemo(()=>entry.expenses.reduce((s,x)=>s+Number(x.amount||0),0),[entry.expenses]);
  const entryProfit=Number(entry.revenue||0)-expenseTotal;
  const iqd=visibleEmployees.filter(e=>(e.salaryCurrency||'IQD')==='IQD').reduce((s,e)=>s+Number(e.salary||0),0);
  const usd=visibleEmployees.filter(e=>e.salaryCurrency==='USD').reduce((s,e)=>s+Number(e.salary||0),0);
  const mode=report?.report_mode||reportOptions.report_mode; const showExpenses=mode==='full'; const showProfit=mode!=='revenue_only';

  if(!current) return <AuthScreen users={users} onLogin={setCurrent} onCreateFirstAdmin={createFirstAdmin}/>;

  return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="brandLogo">RTT</div><div><h1>Royal Thai Touch</h1><span>ERP v0.9.4</span></div></div><nav>{nav('dashboard',<BarChart3 size={18}/>, 'Dashboard')}{nav('entry',<Save size={18}/>, 'Daily Entry')}{nav('reports',<Download size={18}/>, 'Reports',()=>{setPage('reports');setTimeout(loadReport,100);})}{nav('branches',<Building2 size={18}/>, 'Branches')}{nav('employees',<Users size={18}/>, 'Employees')}{nav('social',<Link2 size={18}/>, 'Social Links',()=>{setPage('social'); if(visibleBranches[0]) changeSocialBranch(String(visibleBranches[0].id));})}{nav('audit',<ListChecks size={18}/>, 'Audit Log',()=>{setPage('audit');setTimeout(loadAuditLogs,100);})}{nav('users',<UserCog size={18}/>, 'Users')}{nav('settings',<Settings size={18}/>, 'Settings')}<button onClick={()=>setCurrent(null)}><LogOut size={18}/> Logout</button></nav></aside><main className="content"><header className="topbar"><div><h2>{pageLabels[page]}</h2><p>Logged in as <b className="goldText">{current.username}</b> — {current.role}</p></div><div className="dateBox"><CalendarDays size={18}/><input type="date" value={businessDate} onChange={async e=>{setBusinessDate(e.target.value);await loadData(e.target.value)}}/><button onClick={()=>loadData()}><RefreshCcw size={16}/> Refresh</button></div></header>{message&&<div className="notice">{message}</div>}

{page==='dashboard'&&can('dashboard')&&<><section className="cards"><div className="metric"><span>Revenue Today</span><strong>{formatIQD(visibleRows.reduce((s,r)=>s+r.revenue,0))}</strong></div><div className="metric danger"><span>Expenses Today</span><strong>{formatIQD(visibleRows.reduce((s,r)=>s+r.expenses,0))}</strong></div><div className="metric gold"><span>Net Profit</span><strong>{formatIQD(visibleRows.reduce((s,r)=>s+r.net_profit,0))}</strong></div><div className="metric"><span>Visible Centers</span><strong>{visibleBranches.length}</strong></div></section><section className="panel"><h3>30-Day Trend</h3><Chart data={trend}/></section><section className="panel"><h3>Branch Performance</h3><table><thead><tr><th>Branch</th><th>Revenue</th><th>Expenses</th><th>Profit</th><th>Status</th></tr></thead><tbody>{visibleRows.map(r=><tr key={r.branch_id}><td>{r.branch}</td><td>{formatIQD(r.revenue)}</td><td>{formatIQD(r.expenses)}</td><td>{formatIQD(r.net_profit)}</td><td>{r.status}</td></tr>)}</tbody></table></section></>}

{page==='entry'&&can('entry')&&<section className="entryLayout"><form className="panel entryPanel" onSubmit={saveEntry}><h3>Daily Revenue Entry</h3><label>Allowed Center</label><select value={entry.branch_id} onChange={async e=>{setEntry({...entry,branch_id:e.target.value});await loadEntry(e.target.value,entry.business_date)}}>{visibleBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label>Date</label><input type="date" value={entry.business_date} onChange={async e=>{setEntry({...entry,business_date:e.target.value});await loadEntry(entry.branch_id,e.target.value)}}/><label>Daily Revenue</label><input type="number" value={entry.revenue} onChange={e=>setEntry({...entry,revenue:e.target.value})}/><label>Revenue Notes</label><textarea value={entry.notes} onChange={e=>setEntry({...entry,notes:e.target.value})}/><div className="expenseHeader"><h4>Expenses</h4><button type="button" onClick={addExpense}><Plus size={16}/> Add Expense</button></div>{entry.expenses.map((x,i)=><div className="expenseRow" key={i}><input value={x.category} onChange={e=>updateExpense(i,'category',e.target.value)}/><input type="number" value={x.amount} onChange={e=>updateExpense(i,'amount',e.target.value)}/><input value={x.notes} onChange={e=>updateExpense(i,'notes',e.target.value)}/><button type="button" className="iconBtn" onClick={()=>setEntry(p=>({...p,expenses:p.expenses.filter((_,n)=>n!==i)}))}><Trash2 size={16}/></button></div>)}<button className="primaryBtn">Save Day</button><button type="button" className="secondaryBtn" onClick={closeDay}>Close Day</button></form><div className="panel summaryPanel"><h3>Daily Summary</h3><div className="summaryLine"><span>Revenue</span><strong>{formatIQD(entry.revenue)}</strong></div><div className="summaryLine"><span>Expenses</span><strong>{formatIQD(expenseTotal)}</strong></div><div className="summaryLine total"><span>Net Profit</span><strong>{formatIQD(entryProfit)}</strong></div></div></section>}

{page==='reports'&&can('reports')&&<><section className="panel reportPanel"><h3>Reports</h3><div className="reportControls"><label>From</label><input type="date" value={reportRange.from} onChange={e=>setReportRange({...reportRange,from:e.target.value})}/><label>To</label><input type="date" value={reportRange.to} onChange={e=>setReportRange({...reportRange,to:e.target.value})}/><label>Center</label><select value={reportOptions.branch_id} onChange={e=>setReportOptions({...reportOptions,branch_id:e.target.value})}><option value="">All Allowed</option>{visibleBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label>Content</label><select value={reportOptions.report_mode} onChange={e=>setReportOptions({...reportOptions,report_mode:e.target.value})}><option value="full">Full financial report</option><option value="revenue_profit">Revenue and profit only</option><option value="revenue_only">Revenue only</option></select><button onClick={loadReport}><BarChart3 size={18}/> Show</button><button onClick={()=>window.open(`${API}/reports/excel?${reportQuery()}`,'_blank')}><Download size={18}/> Export Excel</button><button onClick={()=>window.open(`${API}/reports/pdf?${reportQuery()}`,'_blank')}><FileText size={18}/> Export PDF</button></div></section>{report&&<><section className="cards"><div className="metric"><span>Total Revenue</span><strong>{formatIQD(report.total_revenue)}</strong></div>{showExpenses&&<div className="metric danger"><span>Total Expenses</span><strong>{formatIQD(report.total_expenses)}</strong></div>}{showProfit&&<div className="metric gold"><span>Net Profit</span><strong>{formatIQD(report.net_profit)}</strong></div>}</section><section className="panel"><h3>Center Totals</h3><table><thead><tr><th>Center</th><th>Revenue</th>{showExpenses&&<th>Expenses</th>}{showProfit&&<th>Profit</th>}</tr></thead><tbody>{report.branch_totals.filter(r=>visibleBranches.some(b=>b.name===r.branch)).map(r=><tr key={r.branch}><td>{r.branch}</td><td>{formatIQD(r.revenue)}</td>{showExpenses&&<td>{formatIQD(r.expenses)}</td>}{showProfit&&<td>{formatIQD(r.net_profit)}</td>}</tr>)}</tbody></table></section></>}</>}

{page==='branches'&&can('branches')&&<><section className="panel"><h3>Add Branch</h3><form className="inlineForm" onSubmit={createBranch}><input value={branchForm.name} onChange={e=>setBranchForm({...branchForm,name:e.target.value})} required/><input value={branchForm.address} onChange={e=>setBranchForm({...branchForm,address:e.target.value})}/><button><Plus size={16}/> Add Branch</button></form></section><section className="panel"><h3>Visible Branches</h3><table><tbody>{visibleBranches.map(b=><tr key={b.id}><td>{b.id}</td><td>{b.name}</td><td>{b.address}</td></tr>)}</tbody></table></section></>}

{page==='employees'&&can('employees')&&<><section className="cards"><div className="metric"><span>Employees</span><strong>{visibleEmployees.length}</strong></div><div className="metric gold"><span>Monthly Salaries IQD</span><strong>{formatIQD(iqd)}</strong></div><div className="metric gold"><span>Monthly Salaries USD</span><strong>USD {usd.toLocaleString('en-US')}</strong></div></section><section className="panel"><h3>Add Employee</h3><form className="employeeForm" onSubmit={addEmployee}><input required value={employeeForm.name} onChange={e=>setEmployeeForm({...employeeForm,name:e.target.value})} placeholder="Employee name"/><select value={employeeForm.branch_id} onChange={e=>setEmployeeForm({...employeeForm,branch_id:e.target.value})}>{visibleBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={employeeForm.role} onChange={e=>setEmployeeForm({...employeeForm,role:e.target.value})} placeholder="Job"/><input type="number" value={employeeForm.salary} onChange={e=>setEmployeeForm({...employeeForm,salary:e.target.value})} placeholder="Monthly salary"/><select value={employeeForm.salaryCurrency} onChange={e=>setEmployeeForm({...employeeForm,salaryCurrency:e.target.value})}><option value="IQD">Iraqi Dinar IQD</option><option value="USD">US Dollar USD</option></select><input value={employeeForm.phone} onChange={e=>setEmployeeForm({...employeeForm,phone:e.target.value})} placeholder="Phone"/><label>Profile photo<input type="file" accept="image/*" onChange={e=>fileToBase64('profileImage',e.target.files[0])}/></label><label>Passport image<input type="file" accept="image/*" onChange={e=>fileToBase64('passportImage',e.target.files[0])}/></label><label>Residence ID front<input type="file" accept="image/*" onChange={e=>fileToBase64('residenceFrontImage',e.target.files[0])}/></label><label>Residence ID back<input type="file" accept="image/*" onChange={e=>fileToBase64('residenceBackImage',e.target.files[0])}/></label><button><Save size={16}/> Save Employee</button></form></section><section className="panel"><h3>Employees List</h3><table><thead><tr><th>Name</th><th>Branch</th><th>Job</th><th>Salary</th><th>Actions</th></tr></thead><tbody>{visibleEmployees.map(emp=><tr key={emp.id}><td>{emp.name}</td><td>{emp.branch}</td><td>{emp.role}</td><td>{formatSalary(emp)}</td><td><button onClick={()=>setSelectedEmployee(emp)}><FileText size={16}/> View</button><button onClick={()=>printEmployee(emp)}><Printer size={16}/> Print</button></td></tr>)}</tbody></table></section></>}

{selectedEmployee&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.72)',zIndex:9999,display:'flex',alignItems:'center',justifyContent:'center',padding:22}} onClick={()=>setSelectedEmployee(null)}><div className="panel" style={{width:'min(980px,96vw)',maxHeight:'92vh',overflow:'auto'}} onClick={e=>e.stopPropagation()}><div className="splitPanel"><h3>Employee Details</h3><button onClick={()=>setSelectedEmployee(null)}>Close</button></div><p><b>Name:</b> {selectedEmployee.name}</p><p><b>Center:</b> {selectedEmployee.branch}</p><p><b>Salary:</b> {formatSalary(selectedEmployee)}</p><button onClick={()=>printEmployee(selectedEmployee)}><Printer size={16}/> Print</button></div></div>}

{page==='social'&&can('social')&&<><section className="panel"><h3>Social Links</h3><form className="employeeForm" onSubmit={saveSocialLinks}><select value={socialBranchId} onChange={e=>changeSocialBranch(e.target.value)}>{visibleBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={socialForm.facebook} onChange={e=>setSocialForm({...socialForm,facebook:e.target.value})} placeholder="Facebook"/><input value={socialForm.instagram} onChange={e=>setSocialForm({...socialForm,instagram:e.target.value})} placeholder="Instagram"/><input value={socialForm.tiktok} onChange={e=>setSocialForm({...socialForm,tiktok:e.target.value})} placeholder="TikTok"/><input value={socialForm.whatsapp} onChange={e=>setSocialForm({...socialForm,whatsapp:e.target.value})} placeholder="WhatsApp"/><input value={socialForm.website} onChange={e=>setSocialForm({...socialForm,website:e.target.value})} placeholder="Website"/><button><Save size={16}/> Save Links</button></form></section><section className="panel"><table><tbody>{visibleBranches.map(b=>{const s=socialLinks[String(b.id)]||{};return <tr key={b.id}><td>{b.name}</td><td>{s.facebook?<button onClick={()=>openExternal('url',s.facebook)}>Facebook</button>:'-'}</td><td>{s.whatsapp?<button onClick={()=>openExternal('whatsapp',s.whatsapp)}>WhatsApp</button>:'-'}</td></tr>})}</tbody></table></section></>}

{page==='users'&&can('users')&&<><section className="panel"><h3>Add User</h3><form className="employeeForm" onSubmit={addUser}><input required value={userForm.username} onChange={e=>setUserForm({...userForm,username:e.target.value})} placeholder="Username"/><input required type="password" value={userForm.secret} onChange={e=>setUserForm({...userForm,secret:e.target.value})} placeholder="Password"/><select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}><option>Admin</option><option>Manager</option><option>Reception</option><option>Accountant</option><option>Staff</option></select><select value={userForm.active?'active':'inactive'} onChange={e=>setUserForm({...userForm,active:e.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select><button><UserCog size={16}/> Save User</button></form><div className="panel" style={{marginTop:16}}><h3>Page Permissions</h3><div className="buttonGroup">{allPages.map(k=><button key={k} className={userForm.permissions.includes(k)?'':'secondaryBtn'} style={{width:'auto',margin:0}} onClick={()=>togglePermission(k)}>{pageLabels[k]}</button>)}</div></div><div className="panel" style={{marginTop:16}}><h3>Allowed Centers</h3><p style={{color:'#a1a1aa'}}>Leave empty for all centers, or select one/more centers. Daily Entry will show only selected centers.</p><div className="buttonGroup">{branches.map(b=><button key={b.id} className={(userForm.allowedBranches||[]).includes(String(b.id))?'':'secondaryBtn'} style={{width:'auto',margin:0}} onClick={()=>toggleBranch(b.id)}>{b.name}</button>)}</div></div></section><section className="panel"><h3>Users List</h3><table><thead><tr><th>User</th><th>Role</th><th>Centers</th><th>Permissions</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.role}</td><td>{u.allowedBranches?.length ? branches.filter(b=>u.allowedBranches.includes(String(b.id))).map(b=>b.name).join(', ') : 'All Centers'}</td><td>{(u.permissions||[]).map(p=>pageLabels[p]).join(', ')}</td><td><button className="iconBtn" onClick={()=>setUsers(p=>p.filter(x=>x.id!==u.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></section></>}

{page==='audit'&&can('audit')&&<section className="panel"><h3>Audit Log</h3><button onClick={loadAuditLogs}><RefreshCcw size={16}/> Refresh</button><table><tbody>{auditLogs.map(l=><tr key={l.id}><td>{l.action}</td><td>{l.entity}</td><td>{l.created_at}</td></tr>)}</tbody></table></section>}
{page==='settings'&&can('settings')&&<section className="panel"><h3>Settings</h3><p>Users can be restricted to selected centers.</p><p>Daily Entry only displays centers allowed for the logged-in user.</p></section>}
</main></div>;
}

createRoot(document.getElementById('root')).render(<App />);
